### ISSUE TITLE
Initial implementation of a matching algorithm in ChatSearchActivity

### ISSUE THREAD

**Issue by Saharco** [Saharco/YP1-Vedibarta#36]
- Need to start loading as soon as the user hits the "search" button in ChatSearchActivity. User can't interrupt this process, and it has a fixed timeout (~20 seconds?).

- Handle lack of wi-fi connection

- Implement the querying process as a backend service (separate thread!)

- Querying done as a union of nested queries **with random indexing** - see if this is possible (performance? design?)

- Gather the set of potential chat candidates (entire documents from Firebase) and send it in the intent's bundle to ChatCandidatesActivity

**Comment by Saharco** [comment]
duplicate of #32

**Comment by samuelpanzieri** [comment]
@Saharco Can you clarify what is the intended behaviour on lack of wifi?

**Comment by Saharco** [comment]
@samuelpanzieri i created a helper method in VedibartaActivity (not in the develop branch yet) which handles this type of problem: you set a timeout and it displays to the user that it's loading. if the time's up: it displays an error message that takes you back to the previous screen. we can make it so that the behavior can be overridden when "going back to the previous screen" is not a suitable solution
