### ISSUE TITLE
Question Generator

### ISSUE THREAD

**Issue by Grin98** [Saharco/YP1-Vedibarta#61]
Need to find out what are the common hobbies of the students in a chat and generate the appropriate questions

**Comment by Grin98** [comment]
redesign the GUI of the Question Generator dialog

**Comment by Saharco** [comment]
@Grin98 update on this?

**Comment by gilzim** [comment]
- Show question categories by common hobbies categories instead of all categories
- After a category was selected show question related to it based on the common hobbies
-- design the appropriate dialog with animations
-- question selection logic
