### ISSUE TITLE
new design for hobbies table

### ISSUE THREAD

**Issue by gilzim** [Saharco/YP1-Vedibarta#82]
instead of table of bubbles, arrange the hobbies to groups and each group will be presented in a card with an appropriate background

**Comment by Saharco** [comment]
categories: 
ספורט, בילויים, טכנולוגייה, משחקים, אחר

**Comment by Saharco** [comment]
ספורט
מוסיקה
מחשבים
משחקי מחשב
קולנוע
תאטרון
קריאת ספרים
שופינג
חברים
אוכל
ריקוד
אומנות
רובוטיקה
מדעים
מתמטיקה
כדורגל
כדורסל
טניס
שחייה
טיולים
טבע
צילום
ציור
פוליטיקה
סדרות- נטפליקס
בישול
תנועות נוער
אופנה
אופניים
אומנויות לחימה
משחקי לוח
</p>
